name: stray_dog_adoption
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.2

dependencies:
  another_flushbar: ^1.12.30
  auto_route: ^9.2.2
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.5
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dynamic_color: ^1.7.0
  easy_debounce: ^2.0.3
  equatable: ^2.0.5
  file_picker: ^8.1.4
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  injectable: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 23
